language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - pip install .
  - pip install doctest-ignore-unicode
  - pip install pytest
# command to run tests
script:
  - py.test travesty/ tests/
